### ISSUE TITLE
Gallery block: Small gallery images with captions and links are not clickable

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#238]
**Describe the bug**
When a gallery image is very small and has both a link and a caption, the caption covers the clickable area of the image.

**To Reproduce**
1. Add a gallery block to a post or page
2. Add a caption to the image
3. Select one of the link options in the block sidebar
4. Set the gallery so that the images are fairly small
5. save and view the error on the front.

**Expected behavior**
The link needs to be clickable

**Screenshots**
![gallery-link](https://user-images.githubusercontent.com/7422055/94932622-9df5c780-04c9-11eb-8e89-2fff8ec2ec4f.gif)

**Comment by melchoyce** [comment]
Looks like this is a Gutenberg bug — I'm able to reproduce using different themes, including the Gutenberg starter theme. Seems like something we should tackle in Gutenberg itself.

**Comment by carolinan** [comment]
There might be open issues for it in the Gutenberg repo, I did not check, but for now I added the label.

**Comment by carolinan** [comment]
@kjellr I found this Gutenberg issue,
https://github.com/WordPress/gutenberg/issues/24896

Do you know if there is one open for the problem above though?

**Comment by kjellr** [comment]
No, I haven't seen a bug report for the problem described above. I think a fresh one is appropriate.

**Comment by aristath** [comment]
I've been examining this one for a while and the more I look at it the more it looks like this is not an issue.
If users add a small image with large caption, then it's really a problem with the content, not the theme or the editor or the HTML generated.
The one thing I'd suggest doing here is to change the font-size for these from `--global--font-size-sm` to `--global--font-size-xs` so they are `1em` instead of `1.125em`. That will make them fit a little better...

**Comment by carolinan** [comment]
Let's go with reducing the size.
