### ISSUE TITLE
Include the privacy policy link

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#242]
**Is your feature request related to a problem? Please describe.**
The theme does not currently show the privacy policy link.
If we want to show it, where (in the footer) would it be placed?

**Comment by luminuu** [comment]
I think it should always be a part of a menu. In Germany for example, we need another page called "Impressum" with legal details and usually this one and the privacy policy page go together. I always put them in a menu and display them somewhere in the footer.

**Comment by carolinan** [comment]
there is no footer menu :)

**Comment by LittleBigThing** [comment]
Adding the privacy link (in a footer menu) is mentioned in #148 as well.

It could also be added (in the footer) automatically using [`the_privacy_policy_link`](https://developer.wordpress.org/reference/functions/the_privacy_policy_link/). This would be less flexible, however.

Another option would be to have the user add it to a footer widget manually. This could be problematic since the placement of the widgets is not that flexible yet.
