### ISSUE TITLE
IE11: The menu does not work

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#296]
**Describe the bug**
-The toggle button to open and close the responsive menu is not working.
-The toggle button for the submenu items is invisible and does not work.

-I think that for this browser, displaying all menu items without toggle is acceptable.

JS errors:
`twentytwentyoneExpandSubMenu is not defined`

`invalid character on:     mobileButton = document.getElementById( `${ id }-mobile-menu` );`

**Screenshots**
![menu-ie11](https://user-images.githubusercontent.com/7422055/95201865-cc80e480-07e0-11eb-844f-3191093445cf.gif)

**Desktop (please complete the following information):**
 - OS:  Win 10 PC
 - Browser Internet Explorer 11

**Comment by aristath** [comment]
The problem here is the use of syntax non-compatible with IE, particularly the use of backslashes to concat strings.
These issues were fixed in https://github.com/WordPress/twentytwentyone/pull/269 so as soon as that get merged the JS part will be OK.
The CSS part is different, we'll need to do something about these scrollbars 🤔

**Comment by aristath** [comment]
Closing this one as the menu now works in IE.
Styling issues can be addressed in a different ticket.
