### ISSUE TITLE
Pages - How to implement two page heading styles

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#37]
In the design, pages with multiple columns (assumed to be columns blocks in content),
position the page title differently compared to when the content only has a single column.

Single column: Centered page title
Multiple columns: Left aligned wide page title.

How do we best implement this?
Perhaps using a body class?

**Comment by trsenna** [comment]
Hi,

why Is QA harder with two custom page templates than using a checkbox? Don't you have to test CSS changes with checkbox checked and unchecked anyway?

IMHO I'd suggest page-templates 'cause it feels more natural for theme developers. A checkbox can be nice too - but as a developer what Do I do when I need to create a new page-template that has a title always? So maybe now I have to decide if I remove the checkbox options or change my markup and styles to support the feature I do not need. This is the reason why page-templates makes more sense to me.

But probably it's possible for you to make easier for developer to just disable the checkbox button programmatically. In this case it's OK and acceptable for me to go with a checkbox option.

**Comment by pattonwebz** [comment]
> why Is QA harder with two custom page templates than using a checkbox? Don't you have to test CSS changes with checkbox checked and unchecked anyway?

The difference is testing against 2 pages (which are entirely replicated other than just the differnce in title) vs testing against 2 states of the same page. 

For 2 pages we need to test both pages but also ensure any code changes to one template is ported across both templates (since the everything except title markup is replicated). With one page and a toggle we just need to test both states (no code porting required).

**Comment by trsenna** [comment]
Thanks @pattonwebz for your answer :+1: 

But now thinking as just changing the page state - with page templates is it not just changing states of a page too?

**Comment by pattonwebz** [comment]
> with page templates is it not just changing states of a page too?

Sure is, but the template option here comes along with 95% reused code and the need to replicate changes from one into the other every time one is made. 2 checks AND 2 places to copy/paste code between.

**Comment by melchoyce** [comment]
One other issue a page template could help us solve is how to align the heading here, without resorting to creating a new columns block just to contain it:

![image](https://user-images.githubusercontent.com/2846578/94048008-dd713500-fda0-11ea-9519-900be9c04771.png)

**Comment by pattonwebz** [comment]
> One other issue a page template could help us solve is how to align the heading here, without resorting to creating a new columns block just to contain it:
> 
> ![image](https://user-images.githubusercontent.com/2846578/94048008-dd713500-fda0-11ea-9519-900be9c04771.png)

Is the position of this title not the same position as what is in the narrow default template?

**Comment by melchoyce** [comment]
It is, this is testing with the narrow template. I'd like it to look like this:

![image](https://user-images.githubusercontent.com/2846578/94050040-b5370580-fda3-11ea-8339-941d3ad8fb4c.png)

**Comment by pattonwebz** [comment]
Right so the ask is still the same - a template that exists to just move the title?

**Comment by melchoyce** [comment]
So ideally, we'd have wide/full alignment settings for _all_ blocks in Gutenberg so we could control the alignment of text elements as well. In the interim for the theme, I was thinking with a full-width template, all of the content would span the width of the page. This has obvious usability and readability issues, but seems to be the standard for themes that include similar full-width templates?

**Comment by aristath** [comment]
> This has obvious usability and readability issues, but seems to be the standard for themes that include similar full-width templates?

Yes, it is the standard. It's also an extremely bad standard, one that began with themes that wanted to be used with page-builders which were at the time unable to take over the template and were limited to the content area. This hasn't been the case for many years, but themes still keep following this bad standard simply because it is the standard.
Please, let's not follow bad standards just because that's what others are doing... 
The screenshots posted above for a "full-width" template could easily be accomplished with a group block set to align-wide, as the contents inside it would be wider than the default - but not span the entire screen-width (which would be an issue on large screens).

**Comment by melchoyce** [comment]
> The screenshots posted above for a "full-width" template could easily be accomplished with a group block set to align-wide, as the contents inside it would be wider than the default - but not span the entire screen-width (which would be an issue on large screens).

That doesn't work, though:

![image](https://user-images.githubusercontent.com/2846578/94162219-7b720780-fe54-11ea-90d9-f0328bae7520.png)

`wp-block-group__inner-container` inherits the content width.

**Comment by aristath** [comment]
Then perhaps that should be fixed?

**Comment by melchoyce** [comment]
Is that something overwritable by the theme, or is it a Gutenberg issue?

**Comment by luminuu** [comment]
I personally would not want to have the inner elements of the Group block to span the wide/full width as well. I think this is a bad pattern, especially if you want to have elements grouped but still using the default content width.

**Comment by kjellr** [comment]
> Is that something overwritable by the theme, or is it a Gutenberg issue?

It's Gutenberg in the editor, and the theme is mimicking that on the front end. On the Gutenberg side, this was an intentional decision to prevent super-wide text by default. 

The theme _can_ overwrite this, but I'd advise against it for the reasons noted above. 

It would be good to start up a conversation in the Gutenberg repo to figure out a natively-supported solution for this.

**Comment by melchoyce** [comment]
Circling back to the page/post titles: let's consolidate and style every page/post title like this, instead of having the wide-width and narrow styles:

![image](https://user-images.githubusercontent.com/2846578/94563642-fc564800-0234-11eb-8c2a-3a46ab038078.png)

Hopefully, we can tackle the rest of the issues in Gutenberg itself.

**Comment by pattonwebz** [comment]
I like the left aligned title a lot on both views here :) 

This kind of title based change here is certainly much easier with FSE so I expect we can have it working in that version of the theme without any trouble at all.

**Comment by kjellr** [comment]
> Circling back to the page/post titles: let's consolidate and style every page/post title like this, instead of having the wide-width and narrow styles:

I _think_ this is the way things are implemented at the moment, right? If so, we can close this ticket. 

With Featured Image|Without
---|---
![Screen Shot 2020-09-29 at 1 32 01 PM](https://user-images.githubusercontent.com/1202812/94595080-53b9df80-0258-11eb-911f-3682a5407689.png)|![Screen Shot 2020-09-29 at 1 32 30 PM](https://user-images.githubusercontent.com/1202812/94595084-54527600-0258-11eb-889d-add026581940.png)

**Comment by melchoyce** [comment]
Nope, pages still use the constrained-width headings.
