### ISSUE TITLE
Use text-decoration for all link underlines

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentyone#377]
Some of our underlines are actually `border-bottom: 1px`, while others are `text-decoration: underline`. We should change all of these (preferably to `text-decoration`, and add while we're at it we should add a `text-decoration-thickness: 1px` rule for browsers that support it. 

<img width="331" alt="Screen Shot 2020-10-08 at 3 51 40 PM" src="https://user-images.githubusercontent.com/1202812/95507068-dd675c80-097e-11eb-8b84-dbe39422086a.png">

**Comment by SResok** [comment]
This issue was fixed with commits:
e136510114256dd0d3693be8065fd327cdb21c2a 82b34252bced3c4ee48920e65d78e4d44fdc4e6f 91a73a716716183b80e098863407db841b53725d

**Comment by SResok** [comment]
The use of `border-bottom` instead of `text-decoration` was fixed in commits:
e136510114256dd0d3693be8065fd327cdb21c2a 82b34252bced3c4ee48920e65d78e4d44fdc4e6f 91a73a716716183b80e098863407db841b53725d

Created pull-request #392 that will set text-decoration-thickness to 1px for browsers that support it

**Comment by SResok** [comment]
Awaiting response from the a11y team #390

**Comment by carolinan** [comment]
Reopening this issue, it looks like the borders were not removed.
