### ISSUE TITLE
Incorrect alignwide width in editor when the sidebar is open

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentyone#395]
When the editor's sidebar is open, wide-aligned items appear to be wider than they're designed to be (this includes the post title). This occurs at breakpoints between 782px and ~1540px wide.

Current|Expected
---|---
![95369672-bb4ddb80-08a5-11eb-8895-2fb63a962e51](https://user-images.githubusercontent.com/1202812/95625075-e4a56d80-0a45-11eb-815b-b658531a61b0.png)|![95369630-ae30ec80-08a5-11eb-8fa0-f048c9aac634](https://user-images.githubusercontent.com/1202812/95625076-e5d69a80-0a45-11eb-9777-2a739d440ae0.png)

On the "Expected" screenshot, note the extra padding on the left/right side of the post title and the margins. These match the margins available on the front end, and in the editor with the sidebar closed. 

I originally opened #336 to fix this issue, but it introduced more bugs, so we'll need to explore a different approach.

**Comment by SResok** [comment]
Have been looking for a solution for almost 2 hours but haven't found it, placing back into the 'needs action' column

**Comment by ryelle** [comment]
@kjellr Technically this is working correctly — there aren't margins on the element, it's got a max-width + some viewport calculations that mean it's always 200px less than 100% wide. Unfortunately, the inserter & sidebars don't change the viewport width, so they fill in the space that would be margins.

I tried to fix this by changing that max-width or adding set margins when the sidebar is open, but due to the way the editor styles are transformed, this won't work because the `is-sidebar-opened` class is above the wrapper class. We could create a separate CSS file that loads on the editor but does not go through the transform, but either way it's feeling very fragile, with custom breakpoints or relying on the sidebar being a fixed width. It also seems like there isn't class available when the inspector opened, so it would still be an issue there.

I'd recommend closing this, since the workaround would probably introduce more edge cases.

**Comment by kjellr** [comment]
Yeah, I don't think it makes sense to implement a solution that'll be fragile, so closing seems fair for now. Thanks for digging into it too.
