### ISSUE TITLE
WP 5.3 and 5.4 Column custom block style overlap is not working in the editor

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#447]
### Expected behavior

Does the editor and front match?

_**No**_
In the editor, the column with the **overlap style** does not overlap.
They do overlap on the front.

### Editor:

Default width:
![53columns-editor-default-w](https://user-images.githubusercontent.com/7422055/95852109-803f2280-0d53-11eb-8a2d-00a8335774fe.png)

Wide:
![53columns-editor](https://user-images.githubusercontent.com/7422055/95851871-2b9ba780-0d53-11eb-8f3b-b554444f851c.png)

### Front:
![53columns-front](https://user-images.githubusercontent.com/7422055/95852264-c4cabe00-0d53-11eb-9135-ce7152582a67.png)

Editor version (please complete the following information):
WordPress version: 5.3.0 and WordPress version: 5.4.0
Gutenberg version: Not installed

What was used to test (please complete the following information):
OS: Windows 10
Browser: Chrome  86.0.4240.75

**Comment by kjellr** [comment]
I took a quick look at this in 5.3, and I'm not sure it'll be worth fixing — the spacing in the editor is all different because of the added overlap on select. And I'm not sure we'll be able to account for that without impacting the styles in 5.6. I'll give this a closer look during the betas. 

Oddly enough, the starter content overlap _does_ work though. 😄 I think it's because the images on the left are set to be full-width. 

<img width="668" alt="Screen Shot 2020-10-18 at 1 31 33 PM" src="https://user-images.githubusercontent.com/1202812/96375364-a7786400-1146-11eb-86ee-0f06fa453f97.png">

**Comment by aristath** [comment]
I assume this one can be closed?
A lot of things have changed in the editor since WP 5.3, and fixing this will require a lot of juggling without any real benefit for the future.

**Comment by kjellr** [comment]
Yeah, let's close. It can always be opened up later as an enhancement if need be.
