### ISSUE TITLE
Post excerpt/full display setting not used on archive pages

### ISSUE THREAD

**Issue by ryelle** [WordPress/twentytwentyone#454]
**Describe the bug**
I selected "Full text" in the customizer for post display, but I'm still seeing excerpts on archive view.  I saw [the comment on this PR,](https://github.com/WordPress/twentytwentyone/pull/416#issuecomment-707104027) so it sounds like this is intentional, but it seems unexpected to me. I would expect this setting to take effect through the whole site.

**To Reproduce**
1. Go to the Customizer -> Theme settings
2. Select "Full post" & publish
3. View your main posts list, you should see full post content
4. Go to any archive page (category, year, etc)
5. The post content is now just excerpts

**Expected behavior**
If I pick "Full post", I expect to see the full post on all archives.

**Screenshots**

Home:
![Screen Shot 2020-10-13 at 4 07 32 PM](https://user-images.githubusercontent.com/541093/95911667-c7d3a780-0d6f-11eb-8568-d7393746df4b.png)

Year archive
![Screen Shot 2020-10-13 at 4 07 25 PM](https://user-images.githubusercontent.com/541093/95911670-c86c3e00-0d6f-11eb-9e45-867a933739e4.png)

**Comment by melchoyce** [comment]
It looks like Twenty Twenty does it this way, too:

![image](https://user-images.githubusercontent.com/2846578/95912286-a2936900-0d70-11eb-8f38-03741ad7a080.png)

Would be nice to be consistent with both how this setting works on older themes, and also across the posts and archive pages here, since the design is the same.

Sorry if this mixup was on me!
