### ISSUE TITLE
Blocks vertical margins

### ISSUE THREAD

**Issue by briceduclos** [WordPress/twentytwentyone#536]
Currently, all blocks inside .entry-content have a top margin and a bottom margin.
```
.site-main > article > *, .site-main > .not-found > *, .entry-content > *, [class*="inner-container"] > *, .wp-block-template-part > * {
    margin-top: var(--global--spacing-vertical);
    margin-bottom: var(--global--spacing-vertical);
}
```

Is there a reason to add a top margin? (Previous default themes set the top margin to 0). I’m asking because when the user inserts a small spacer block (e.g 20px, the minimal value) between two blocks, the space is very large (20px + 2* spacing-vertical = 80px).

**Comment by kjellr** [comment]
I don't have a strong opinion on this one. Twenty Nineteen used top and bottom margins. Twenty Twenty did not. 

There are a handful of Gutenberg blocks that don't ship bottom margins by default on the front end (like the Group block for example). This causes issues when a theme doesn't account for that. In fact, while looking into this, I just noticed that being an issue on the Twenty Twenty demo: 😅 

![Screen Shot 2020-10-16 at 9 15 18 AM](https://user-images.githubusercontent.com/1202812/96262675-1eb7c780-0f90-11eb-8c87-4e19becacd17.png)

For Twenty Twenty-One this point, I'd suggest taking a lighter touch — since we're so close to beta I'd prefer not to rock the boat with the global margins too much. But if someone would like to try it out and see, I'd be happy to take a look. 

Either way, I do think it'd be a good idea to remove the margins from the spacer block.

**Comment by aristath** [comment]
> Either way, I do think it'd be a good idea to remove the margins from the spacer block.

I agree for the spacer block. Not for all others, but an exception for spacers should be made :+1:

**Comment by pattonwebz** [comment]
Yup seems like a great call to make to remove margins from the spacer at least :)

**Comment by kjellr** [comment]
I'll open a quick PR to handle that.

**Comment by kjellr** [comment]
Actually — we do that already. 😂 

https://github.com/WordPress/twentytwentyone/blob/e0486a21ce723aee3c99d4bdca1331abd31134e6/assets/sass/05-blocks/spacer/_style.scss#L4-L5

**Comment by pattonwebz** [comment]
Nice, seems someone already considerd this before us. That person was smart :)

**Comment by briceduclos** [comment]
Removing the spacer's margins doesn't change anything because that's the blocks' margins around the spacer that create the spacing.  In fact, you can let the margins for the spacer because of margin collapsing.

**Comment by aristath** [comment]
Hmmm so you're saying we need something like this?

```css
* + .wp-block-spacer,
.wp-block-spacer + * {
  margin-top: calc(0 - var(--global--spacing-vertical)) !important;
}
```

**Comment by kjellr** [comment]
Note that if we did do something like that, we'd need it to be applied to the editor as well — the primary goal is to make sure the space matches in both places.

**Comment by ryelle** [comment]
I just noticed this with image blocks, no bottom margin here:

![Screen Shot 2020-10-19 at 12 50 16 PM](https://user-images.githubusercontent.com/541093/96481871-a6f4d180-1209-11eb-99d0-57b8239804f2.png)

Really I noticed it because the post format view doesn't have a bottom margin, which would use the default image block spacing, if it existed.

![Screen Shot 2020-10-19 at 12 51 01 PM](https://user-images.githubusercontent.com/541093/96482254-bffd8280-1209-11eb-98c4-dbb17a627cfa.png)

This doesn't match the editor, there is space there (WP 5.5.1, no GB):

![Screen Shot 2020-10-19 at 12 52 48 PM](https://user-images.githubusercontent.com/541093/96483219-0357f100-120a-11eb-8d31-056456035d81.png)

**Comment by carolinan** [comment]
I labeled this as bug _for the part where the image vertical spacing is inconsistent between the front and editor._

There does not seem to be consensus for the other blocks in entry-content.

**Comment by aristath** [comment]
For images I'm not sure which of the 2 we want... Do we want them to have a bottom margin or not? Judging from the code we already have I'm inclined to say not, but before I start tweaking can anyone confirm that?

**Comment by kjellr** [comment]
I think we do want them to have a bottom margin — I could be wrong, but I believe the only blocks that should have no bottom margin are Cover, Group, Spacer, and Media & Text. (That's just based on my memory of what Gutenberg does by default, so it could use a gut check from someone else).

**Comment by carolinan** [comment]
All new images have the class size-large (even if they are small...) These new images does have a bottom margin.

But the old images from the unit test, as in the screenshot above, does not have the class, and does not have a bottom margin.

**Comment by carolinan** [comment]
The old images in the theme unit test, in the screenshots above, does not have the same markup as the images do today.
New images has the bottom margin, the old one does not.

Current:
`<figure class="wp-block-image size-large"><img loading="lazy" width="165" height="210" src="http://localhost:8888/wp-content/uploads/2014/01/spectacles-17.gif" alt="" class="wp-image-1692"></figure>`

Old:
`<div class="wp-block-image"><figure class="aligncenter"><img src="http://localhost:8888/wp-content/uploads/2013/03/image-alignment-580x300-18.jpg" alt="Image Alignment 580x300" class="wp-image-906"></figure></div>`

**Comment by carolinan** [comment]
So what is needed here is a bottom margin for the old image markup.

**Comment by ryelle** [comment]
I can also replicate it by centering an image. It looks like these lines are to blame:

https://github.com/WordPress/twentytwentyone/blob/e580895d9ec57a3c21048b29c8efcc1ebddd46a8/assets/sass/05-blocks/image/_style.scss#L22-L32

^ These only take effect when the class name is exactly `wp-block-image`, which it is when an image has a left/right/center alignment. It really should only happen when the image is left or right aligned… but those classes are on nested elements inside the div, so we can't differentiate at this level.

So the current issue is that center-aligned images remove the top margin of the following tag.

**Comment by carolinan** [comment]
This seems to be the place to gather vertical spacing issues, so:

When two full width Media & Text blocks are placed after one another, there is vertical spacing on the front, but not in the editor.

**Comment by carolinan** [comment]
When two full width cover blocks are placed after one another, there is vertical spacing on the front, but not in the editor.

**Comment by aristath** [comment]
Moved to the RC1 milestone

**Comment by carolinan** [comment]
I am no longer able to reproduce this problem with the images.
I am using 5.6-beta3-49486 with and without Gutenberg 9.3.0-rc.1 



> I just noticed this with image blocks, no bottom margin here:
> 
> ![Screen Shot 2020-10-19 at 12 50 16 PM](https://user-images.githubusercontent.com/541093/96481871-a6f4d180-1209-11eb-99d0-57b8239804f2.png)
> 
> Really I noticed it because the post format view doesn't have a bottom margin, which would use the default image block spacing, if it existed.
> 
> ![Screen Shot 2020-10-19 at 12 51 01 PM](https://user-images.githubusercontent.com/541093/96482254-bffd8280-1209-11eb-98c4-dbb17a627cfa.png)
> 
> This doesn't match the editor, there is space there (WP 5.5.1, no GB):
> 
> ![Screen Shot 2020-10-19 at 12 52 48 PM](https://user-images.githubusercontent.com/541093/96483219-0357f100-120a-11eb-8d31-056456035d81.png)
