### ISSUE TITLE
inconsistent styling for gallery block (linked and unlinked)

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwentyone#558]
When images are not loading (these are imported from a sandbox site that is gone), there is no indication of a missing image. The outline on the image is apparently from the link.

**Expected behavior**
I expect the images to look the same whether they are linked or not.
I also expect to see some indication of a missing image.

**Screenshots**
This shows the same images in two gallery blocks. The first has linked images and the second does not.
![my gallery test – Local Current WP-16](https://user-images.githubusercontent.com/7957680/96295742-c0044500-0fb3-11eb-88ee-b28efa45ec4c.jpg)

**Comment by carolinan** [comment]
There was an earlier discussion on if linked images need an indicator for accessibility reasons, but no consensus was reached.

**Comment by melchoyce** [comment]
Hey Joy, what browser is this? I can't replicate the outline on Chrome, Firefox, or Safari.

**Comment by hedgefield** [comment]
I agree a broken image should warrant some kind of indication or graphic. Could we add something like that? I'm thinking of the icon of an image with a tear in the middle, or simple a cross and maybe a subtle background color. Quick mockup:

![broken](https://user-images.githubusercontent.com/6073772/96738275-d6007400-13be-11eb-9dc8-f34ee0c85974.jpg)

As for the borders, I don't see them either on the TT1 version I installed earlier today.

**Comment by joyously** [comment]
Mel, I was using Firefox 81.0 on Ubuntu. (I have since updated Firefox to 81.0.2.)

@hedgefield, careful not to make use of icons since it would require markup. Images are replaced elements, so :before and :after don't work, especially when there is no image.

**Comment by melchoyce** [comment]
What I'm seeing in Chrome and Firefox:

![image](https://user-images.githubusercontent.com/2846578/96757750-da6b6380-13a3-11eb-80ea-c19eddf623b6.png)
![image](https://user-images.githubusercontent.com/2846578/96757832-fa028c00-13a3-11eb-81b6-0f997e22b94a.png)

I am seeing that border now, so it's likely tied to a browser's broken image styling (rather than the link styling, since these images aren't linked). 

Maybe we could style the broken images so we have a solid background color and/or border, the broken image icon (if it exists in the browser) is vertically/horizontally centered, and the alt text is also vertically centered. Here are two options:

<img src="https://user-images.githubusercontent.com/2846578/96758494-d855d480-13a4-11eb-8e3f-b36d4c1a60c9.png" width="700" />

<img src="https://user-images.githubusercontent.com/2846578/96758698-16eb8f00-13a5-11eb-8bf9-f1da72a93d6f.png" width="700" />

**Comment by joyously** [comment]
If you choose to use a background color, be sure to test with a semi-transparent PNG.

**Comment by melchoyce** [comment]
Good note 👍 

I wonder if we could use JS to apply a custom "broken image" class we could style, instead of styling all images? That could protect against transparent image/background color clashes. I'm finding this on CSS-Tricks: https://css-tricks.com/snippets/jquery/better-broken-image-handling/

**Comment by aristath** [comment]
> I wonder if we could use JS to apply a custom "broken image" class we could style, instead of styling all images?

Yes, we could. But I don't think we should... If there are missing images then that's a problem with the content, not a problem with the theme. It is not the theme's responsibility to fix bugs in the content, the author should just go in and fix the images that are missing.

**Comment by carolinan** [comment]
Unless the reason is to improve accessibility, and the purpose is clearly stated, I feel that this issue should be closed.

**Comment by melchoyce** [comment]
The alt message shows as-is, so I'm fine with closing this 👍
