### ISSUE TITLE
RTL: email and url inputs should always be LTR

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwentyone#564]
Even in RTL mode, email and url inputs should always be left to right.

![RTL-inputs](https://user-images.githubusercontent.com/7957680/96317269-71b36e00-0fd4-11eb-8f3f-91dd5931a53a.jpg)

**Comment by carolinan** [comment]
Background to why the mentioned fields need to be LTR:

https://codex.wordpress.org/Right_to_Left_Language_Support#Special_Cases

_Some fields should be Left To Right direction in both LTR and RTL languages, For example : email, telephones, zip codes, codes, URLs and any input contains English letters and numbers, So it is better to assign a unique id or class to each input fields, which you will be able to make them LTR direction in CSS files_

**Comment by aristath** [comment]
I don't think the theme should do anything specific for these...
email-fields and in general fields that have a specific type should (and I _think_ are but am not certain) taken care of by default in browsers.
If a plugin uses `type="text"` instead of `type="email"`, then that plugin should take care of its own styles.
Are these fields right-aligned, or actually LTR? The alignment should be OK, LTR input direction when actually typing a value would not be ok :thinking:

**Comment by joyously** [comment]
The `direction:ltr` style can be by attribute, so that it is always handled. Obviously, the browser does not do it, as you can see by the screenshot.
