### ISSUE TITLE
Visibility issues with dark theme preference

### ISSUE THREAD

**Issue by briceduclos** [WordPress/twentytwentyone#592]
**Describe the bug**
#528 added the dark mode preference to the theme. When testing this mode, I encounter several issues (the test was made with the background color set to white inside the Customizer):
- inside a group with light gray background color (custom color #f5f5f5), the text inside is also light-gray therefore unreadable
- if the site logo is dark, it becomes nearly invisible, same for illustration like https://opendoodles.s3-us-west-1.amazonaws.com/dancing.png
- the social icons inside the footer are still dark
- inside the editor, the dark theme isn’t applied, so there’s a difference between the front and the back.

IMHO, even if it was working perfectly, the user should have a Customizer option to turn this off as it can really change the website design without him knowing.

**Screenshots**
| "Normal" mode  | Dark theme |
| ------------- | ------------- |
| ![normal-mode](https://user-images.githubusercontent.com/56188815/96458765-9bada000-1221-11eb-9b44-90a769d8e241.PNG) ![normal-mode-footer](https://user-images.githubusercontent.com/56188815/96459137-0c54bc80-1222-11eb-8d1b-9a6baa933dcb.PNG)  | ![dark-mode](https://user-images.githubusercontent.com/56188815/96458767-9c463680-1221-11eb-93fa-1ef81fbd95b0.PNG) ![dark-mode-footer](https://user-images.githubusercontent.com/56188815/96459141-0ced5300-1222-11eb-8fdc-9fed3ce15287.PNG) |

**Comment by carolinan** [comment]
Please split this into separate issues, the social icon color problem is not only present when the user has a preference set.
I am going to assume that this is the menu, not the social icon block?

**Comment by carolinan** [comment]
_if the site logo is dark, it becomes nearly invisible,_  
That is not up to the theme, but I agree there needs to be some information on the themes support page that the theme has support for _prefers-color-scheme_

**Comment by ryelle** [comment]
> inside a group with light gray background color (custom color #f5f5f5), the text inside is also light-gray therefore unreadable

This is also a problem when a dark background color is selected by the user, the only difference is that it's obvious in the editor since the dark background is used here too. It's a custom color, we have no way of knowing whether it's light or dark to programmatically change the text color.

> inside the editor, the dark theme isn’t applied, so there’s a difference between the front and the back.

If the user has the dark-mode setting on, the editor should show the dark scheme, so this should be updated. (unless this was an intentional decision? maybe this needs core/gutenberg support)

But… this means that there will still potentially be a difference between site-owner & site-visitor, if one requests the dark mode and the other doesn't. I agree that documenting this will be very important.

> the user should have a Customizer option to turn this off as it can really change the website design without him knowing.

Hm, technically this is an accessibility feature, to support users who request the site in dark mode, so I don't know if allowing it to be disabled is a good idea… but it could be a place to expose that this feature exists. Something like this in Background Color panel, maybe?

- [x] Support visitor's color scheme preference

**Comment by carolinan** [comment]
I believe all issues here has been addressed with the updates to the dark mode settings. 
I will close this and if I was wrong please feel free to request to reopen it or create a new issue describing the remaining problem.
