### ISSUE TITLE
Columns block on dark background, invisible ink

### ISSUE THREAD

**Issue by bph** [WordPress/twentytwentyone#685]
In this video you see me trying to drag and drop a paragraph into a columns block that's above the paragraph, with two 50/50 columns. 

When I start dragging the paragraph to a column, I hard can see where I am going. Although there is a light outline of the paragraph at the beginning, the column block doesn't have a light outline and the blue on black is barely invisible. 
Also, the blue landing zone color is barely visible on this dark background. 

**To Reproduce**
1. Use a dark default color - I used #303030
2. Create a columns block with two columns
2. Create a paragraph block 
3. Drag & drop the paragraph block into one of the columns. 

**Expected behavior**
I would expect the block outlines to switch to a light color on dark background.

**Screenshots**
Video https://recordit.co/rwoBomnXTU

**Editor version (please complete the following information):**
- WordPress version: trunk (5.6. beta someting]
- Gutenberg zip from Master 10/23/20]

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6
 - Browser Google Chrome
 - Version 86.0.4240.80

**Comment by aristath** [comment]
Looks more like an editor issue than a theme issue to me :thinking: 
If the background color is dark, we switch the editor to dark mode: https://github.com/WordPress/twentytwentyone/blob/e580895d9ec57a3c21048b29c8efcc1ebddd46a8/functions.php#L129-L131

Judging from the video, it looks like the dark editor styles have been somewhat neglected/overlooked lately. Unless I misunderstood what you were referring to and you think this is something that should be fixed in the theme?

**Comment by carolinan** [comment]
Yeah I was just testing this with other black colored themes. 
It is an editor issue, I agree it can be improved but did not find an open issue about it in the Gutenberg repository.
It looks like the preferred way is to open one for each block, but since this is the placeholder one could be open for the placeholder only.

Related issues:
https://github.com/WordPress/gutenberg/pull/25796 (fixed)
https://github.com/WordPress/gutenberg/issues/16732

Closing this, adding the Gutenberg label.
