### ISSUE TITLE
Testing and adjusting WP default blocks

### ISSUE THREAD

**Issue by luminuu** [WordPress/twentytwentyone#72]
Twenty Twenty One uses the default block styles that are provided by WP core. For the release of the theme we need to check that every block is working well with the theme and add adjustments if needed. The list only contains blocks that have an output.

### Text
- [x] Paragraph
- [x] Heading
- [x] List
- [x] Quote
- [x] Code
- [x] Classic
- [x] Preformatted
- [x] Pullquote
- [x] Table
- [x] Verse

### Media
- [x] Image
- [x] Gallery
- [x] Audio
- [x] Cover
- [x] File
- [x] Media & Text
- [x] Video

### Design
- [x] Buttons
- [x] Columns
- [x] Group
- [x] Separator
- [x] More

### Widgets
- [x] Archives
- [x] Calendar
- [x] Categories
- [x] Latest Comments
- [x] Latest Posts
- [x] RSS
- [x] Search
- [x] Social Icons
- [x] Tag Cloud

**Comment by carolinan** [comment]
The text category blocks has been tested in post content and in the widget area, **but not inside columns or group blocks**. 
Issues has been created for the problems that were found.  
Notes: The list block looks broken when added in the widget screen itself, but works well on the front.

**Comment by carolinan** [comment]
I did not find time to test the following today:
Latest Comments
Latest Posts
Columns-tested 5/10
Group
Image -tested 2/10
Gallery -tested 2/10
Cover
Media & Text -tested 2/10

**Comment by carolinan** [comment]
What we are testing/looking for here are:

Blocks that look different in the editor and the front.
Blocks that do not align correctly (widths, left, right)

Blocks with color settings, where the body background color option in the customizer, which also affects the primary text color; affects the readability.
For example light text on light backgrounds.

**Comment by francescamarano** [comment]
Hello everyone! 
I have started to test some of these blocks without knowing about this ticket, so it's not very focused: https://francescatest.com/first-impressions-without-having-seen-the-demo/

October 8th and 9th I will be busy with an online conference, but from Monday I can take a more structured approach to this and dedicate a good chunk of time. 
Adding all the blocks into one post is very confusing, so I changed my checklist as follows.

### To reproduce
1. Create a new post or a page for each block you want to test. Title: name of the block in English.
2. Add the block and use the default settings.
3. Save draft and go preview the post/page. Notice how the blocks look like in the front-end. Take screenshots.
4. Change the settings of the block, if available, and repeat step 3 until you test all options.

### Expected behaviour
For the editor to match the preview.

### Screenshots
Add screenshots of the editor view and the preview.

### Editor version (please complete the following information):
WordPress version:
Gutenberg version: 

### What was used to test (please complete the following information):
OS: 
Browser:
(Possibly screen resolution? I used to test that always when I was still making websites)

**Comment by carolinan** [comment]
tested and opened issues for the Media & text block.
