### ISSUE TITLE
Left or right aligned images are the wrong size on the front.

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#737]
**Describe the bug**
When an image is left or right aligned in the editor, the max width is reduced: 

```
.editor-styles-wrapper .wp-block[data-align="left"] > * {
    max-width: 290px;
    margin-right: var(--global--spacing-horizontal);
}
```

On the front, the max width of the image is depending on _multiple styles_, including:

```
.entry-content img {
    max-width: 100%;
}
.wp-block-image img {
    max-width: 100%;
}
```

**To Reproduce**
1. Add two image blocks to the editor. It does not matter if the blocks are the only blocks, or for example placed in between text.
2. Align the image to the left and right respectively.
3. View the size in the editor, and save.
4. View the front and compare the size.
5. See error

**Expected behavior**
The editor and front should match.

**Screenshots**¨
Editor:

![image-left-editor](https://user-images.githubusercontent.com/7422055/97559703-1161fa80-19de-11eb-9101-b7c73b3fe9c6.png)

Front:
![image-left-front](https://user-images.githubusercontent.com/7422055/97560155-9c42f500-19de-11eb-94fc-3cd687c778da.png)

**Editor version (please complete the following information):**
WordPress version: 5.6-beta2-49360
Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default?
"default"

**Comment by jasmussen** [comment]
Looks like this PR outputs some baseline styles for image blocks: https://github.com/WordPress/gutenberg/pull/8399

Specifically this rule:

```
.wp-block-image img {
    max-width: 100%;
}
```

It looks like the following rule is not from Gutenberg:

```
.entry-content img {
	max-width: 100%;
}
```

... perhaps that's a TwentyTwentyOne rule.

Without testing TwentyTwentyOne and reproducing, it looks like you need to increase the specificity when left aligned. 

There is a separate discussion on whether Gutenberg is too opinionated in providing that max-width responsive rule in the first place, but this is difficult due to the amount of time that rule has been in place.

**Comment by lwangdu** [comment]
entry-title and entry-content width seems off. Here is the screen shoot.
![Screen Shot 2020-10-30 at 9 20 53 AM](https://user-images.githubusercontent.com/24829573/97730879-abcf4600-1a91-11eb-9ca2-1c5dffc285e4.png)
