### ISSUE TITLE
Pullquote: Quotation mark positioning regression

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyone#759]
**Describe the bug**
The text overlaps the quotation mark in the Pullquote block now:

![image](https://user-images.githubusercontent.com/2846578/97736782-90286780-1ab2-11eb-83af-f4fd9251d951.png)

**To Reproduce**
1. Make a new post or page.
2. Add a pullquote block.
3. See that the quotation mark overlaps the text now.

**Expected behavior**
It should look like this:

![image](https://user-images.githubusercontent.com/2846578/97736989-ccf45e80-1ab2-11eb-8881-777259794bb4.png)
https://2021.wordpress.net/2020/10/16/a-love-of-nature/

**Editor version (please complete the following information):**
- WordPress version: 5.6-beta2-49360
- Gutenberg: 9.2.2

**Comment by joyously** [comment]
Is this quotation mark localized like
("") in English, low quotes (,,") in German, and guillemets (<<>>) in French

See https://en.wikipedia.org/wiki/Quotation_mark#Summary_table
and https://jakubmarian.com/map-of-quotation-marks-in-european-languages/

**Comment by melchoyce** [comment]
Can it be? That would be rad.

**Comment by pattonwebz** [comment]
I am pretty sure it's done via a CSS entity and probably doesn't account for i18n. Not sure of the method to make it internationalized other than adding the quotation inline to the page and wrapping it with a translation function.

It would be really, really, nice if we could make this happen though :)

**Comment by joyously** [comment]
It's not really part of this issue, but it might affect the position.
It could be done with the lang attribute on the html tag, but it would be a long selector for all the languages that use each one.
Or you could make it part of the dynamic CSS that is generated. 
Or you could style it with a border instead of a quote. It wasn't styled when I last tested the theme, so I don't know if it's doing it correctly. (some themes have a rule for openquote and not closequote, so nested quotes mess things up)
