### ISSUE TITLE
Dark Mode support toggle: Toggle + content disappeared in Customizer

### ISSUE THREAD

**Issue by sarahricker** [WordPress/twentytwentyone#848]
**Describe the bug**

While testing about in the 5.6 Beta 4 release, it seemed that the Dark Mode support toggle + content disappeared after clicking through responsive design modes and /or colors  in customizer. It never came back until refresh. Upon further inspection, it actually seemed to be happening based on the color choice, which was much more repeatable than the initial impression. 

- Question: Not sure if user should be able to toggle customizer PER view (ie: different settings for mobile vs. desktop)?
- Question: Not sure if user is being purposefully limited to restrict certain colors?

The thing about Dark Mode support is that you're not just supporting turning on DARK colors for a light site, you're also supporting toggling on LIGHT colors for a Dark site, so all colors would have an inverted color to match. Toggling would then just let you "switch" which version you're on based on users device setting. (Some, like the Samsung Galaxy S20 let you set it to automatically switch to match the time of day). 

**To Reproduce**

1. Install 5.6 Beta 4 and activate TT1 theme
2. Visit customizer > Colors & Dark Mode
3. Toggle Dark Mode Support on / off / on
4. Change the color a few times (and maybe change responsive design icons to tablet / mobile )
5. Observe the Dark Mode option disappear. 😱 
6. Return to desktop mode, observer Dark Mode option + text is still gone.
7. Refresh page / customizer, observe Dark Mode has returned! 😸 

**Expected behavior**

- Dark Mode option should always be available in all customizer views. 
- Minimum: User should either see the dark mode checkbox on all views OR should probably have some info text added when dark mode option is removed to explain why? (i.e. _Your current options to not support dark mode_ ). I think "disabling" the checkbox would be more understandable than removing it, if that is the case. 

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.5.1]
-- 5.6 Beta 4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]
-- default
- If the Gutenberg plugin is installed, which version is it? [e.g., 8.9]
-- n/a
**Desktop (please complete the following information):**
-- Mac OS Catalina 10.15.7
-- Chrome Version 86.0.4240.183 (Official Build) (x86_64)

~**Smartphone (please complete the following information):**
 - Version [e.g. 22]~

**Additional context**

This also affects the dark mode toggle at the bottom right screen. Overall difficult to explain through screenshots / report, happy to jump on a chat in case I'm missing something! 🙏

**Comment by aristath** [comment]
> The thing about Dark Mode support is that you're not just supporting turning on DARK colors for a light site, you're also supporting toggling on LIGHT colors for a Dark site, so all colors would have an inverted color to match.

That's not what we're supporting. The theme calls this "Dark Mode Support" and not "Color Schemes Switch" for good reason.
"Light" mode is the default in the web and all devices. That's how the web always worked. If the designer picks a dark color for their background, then the assumption is that they want that specific dark background-color. If we allow dark themes to switch to light, then we run into another issue: Light colors are far more discernible than dark colors. Which means that we can't just default to the mint-green color, as that has a bigger chance of not matching the designer's expectations. Which in turn means that a 2nd colorpicker would need to be added so that users can select separate colors for light & dark modes. But that can lead to a whole new set of problems as they'll be able to pick whatever color combos they want, and cause a11y issues. 
The current implementation may not offer the freedom that some will want, but it is the safest and most robust method. As a default theme, TT1 needs to enforce some best practices while avoiding the pitfall of adding too many options - as all previous default themes historically did.
With that in mind, the theme has a plethora of css-variables that designers can use to further customize things. So if they want to customize the dark mode background-color, they can simply add this in their custom-css field in the customizer:
```css
.respect-color-scheme-preference.is-dark-theme body {
   --global--color-background: #000;
}
```

**Comment by carolinan** [comment]
I believe that the current solution is the best option for now.
