### ISSUE TITLE
Impossible to display a button on dark background as the colors are overridden by the theme on hover

### ISSUE THREAD

**Issue by briceduclos** [WordPress/twentytwentyone#866]
For the button block’s hover state, the theme always overrides the colors selected by the user (with !important). Therefore the user can’t display a button on a dark group or a cover. 

IMHO, the colors entered by the user should stay the same on hover. If the user sets a button to be “fill blue”, it should be “fill blue” on hover.

**Screenshots**
| Buttons with colors set by the user  | Buttons on hover |
| ------------- | ------------- |
| ![button1](https://user-images.githubusercontent.com/56188815/99906861-b7e9a480-2cd9-11eb-9361-5fdf708b6cb7.PNG) | ![button2](https://user-images.githubusercontent.com/56188815/99906866-bf10b280-2cd9-11eb-9667-c4ec32925542.PNG) |

**To reproduce**
Inside the code editor, paste the following code. 

```
<!-- wp:group {"align":"wide","backgroundColor":"black"} -->
<div class="wp-block-group alignwide has-black-background-color has-background"><div class="wp-block-group__inner-container"><!-- wp:buttons {"align":"center"} -->
<div class="wp-block-buttons aligncenter"><!-- wp:button {"style":{"color":{"background":"#1c5cef"}},"textColor":"white"} -->
<div class="wp-block-button"><a class="wp-block-button__link has-white-color has-text-color has-background" style="background-color:#1c5cef">Learn more</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:group -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:cover {"url":"https://raw.githubusercontent.com/WordPress/twentytwentyone/trunk/assets/images/in-the-bois-de-boulogne.jpg","minHeight":300,"align":"wide"} -->
<div class="wp-block-cover alignwide has-background-dim" style="background-image:url(https://raw.githubusercontent.com/WordPress/twentytwentyone/trunk/assets/images/in-the-bois-de-boulogne.jpg);min-height:300px"><div class="wp-block-cover__inner-container"><!-- wp:buttons {"align":"center"} -->
<div class="wp-block-buttons aligncenter"><!-- wp:button {"style":{"color":{"background":"#1c5cef"}},"textColor":"white"} -->
<div class="wp-block-button"><a class="wp-block-button__link has-white-color has-text-color has-background" style="background-color:#1c5cef">Learn more</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover -->
```

**Comment by carolinan** [comment]
We already tried this and it caused a lot of problems as you might remember.

The button can not be identitical in its default state, hover, or focus states, and needs to match the design. 

You are welcome to give it another try in a pull request.

**Comment by carolinan** [comment]
I had time to test the sample content today. 
The default button color is not usually black on black; is Dark Mode on or off, is the body background color changed? 
Just asking so that we can narrow down the issues.

---

With the default mint green body background color, 
the default button color is invisible when placed over a background that uses the grey palette color.
This can be addressed by checking for the parent background color, but only when a named palette color is used.

---

Transparent items over images are always difficult. 
In the case of the cover block, we could possibly check that the block does **not** have the has-background class, but there is no CSS class that tells us if the block has an image. 
The editor has a data-url, but the front only has the style attribute to indicate that there is an image.

Here is why I would rather not rely on the has-background class not being present:
https://github.com/WordPress/gutenberg/issues/21439
