### ISSUE TITLE
Changing image block size does not change caption placement.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwentyone#890]
**Describe the bug**
I am using the newest version of the theme 2021.

Changing the Image size of the Image block to Medium or Thumbnail does not move the caption to stay centered below the image.

![Screen Shot 2020-11-25 at 16 50 37](https://user-images.githubusercontent.com/5323259/100252009-b28d9380-2f3f-11eb-964e-137c480dc811.png)

![Screen Shot 2020-11-25 at 16 50 49](https://user-images.githubusercontent.com/5323259/100252026-b5888400-2f3f-11eb-87ad-bb2847e72fed.png)

**To Reproduce**
1. Add an Image block and an image with a caption through the media library.
2. See the caption centered below the image on "Large" and "Full Size"
3. Change the Image size to Medium or Thumbnail.
4. Notice the caption stay in the same place. Caption does not stay centered below the image.

**Expected behavior**
I expect the caption to stay centered below the image for all image sizes.

**Screenshots**

![Image-caption-2021](https://user-images.githubusercontent.com/5323259/100251818-79552380-2f3f-11eb-9b35-257096605081.gif)

WordPress: 5.5.3
No plugins activated.

---

The same result with Gutenberg plugin 9.4.1 activated.

**Comment by carolinan** [comment]
This seems to be a long-standing **editor** issue that has already been reported in the Gutenberg repo.
It is because the image is resized, but the wrapper is not.

Please remember to include references to your previous issues:
https://github.com/WordPress/gutenberg/issues/13684
https://github.com/WordPress/gutenberg/issues/17162

I found another recent reference here but I don't think a new issue was created. @tellthemachines may be able to confirm.
https://github.com/WordPress/gutenberg/pull/26376#pullrequestreview-522174290

I tried the various margin and `display: table-caption` tricks mentioned in these issues/pull requests with no luck. 
With `display: table` on the wrapper when resized, the image itself is not aligned.
With `display: table-caption` on the figcaption, the text is too narrow and left aligned instead of centered.

![caption](https://user-images.githubusercontent.com/7422055/100329590-28404080-2fce-11eb-94be-e0185feb086a.png)

**Comment by tellthemachines** [comment]
> I found another recent reference here but I don't think a new issue was created. @tellthemachines may be able to confirm.
> [WordPress/gutenberg#26376 (review)](https://github.com/WordPress/gutenberg/pull/26376#pullrequestreview-522174290)

WordPress/gutenberg#17162 reports the issue I mentioned above, so I didn't open a new one. [This comment](https://github.com/WordPress/gutenberg/issues/13684#issuecomment-465473023) explains some of the complexities behind it. Doesn't mean we shouldn't try to fix it though 😄
