### ISSUE TITLE
The scroll bar of the right sidebar is appearing and dissipating when the height of a browser window between 775-787 px

### ISSUE THREAD

**Issue by oglekler** [WordPress/twentytwentyone#891]
**Describe the bug**
The scroll bar of the right sidebar is appearing and dissipating when the height of a browser window between 775-787 px

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page or post
2. Click to add block pattern
3. Resize your window to size between 775-785

Video: https://yadi.sk/i/Ytk0qlzyObB96g

**Comment by carolinan** [comment]
Hi
There are several related issues in the Gutenberg GitHub repository, (https://github.com/WordPress/gutenberg/issues/26936).

I am only able to reproduce it with the columns blocks:

- It only happens when the outer columns block is selected
- It does not matter if the column is from a block pattern or not.
- The height of the content inside the columns does not matter, it also happens if the block is empty.
- **If I delete the registration for the columns block style, the problem disappears, so this narrows it down for further testing.**
- It does not matter if the block style that is registered by the theme is used or not.
- **Deleting the CSS that is used by the registered style did not change anything**
- It does not matter if the CSS in the block style is inline or not.

I tested other themes both with and without custom styles registered for the columns block without being able to reproduce the problem with those themes.

**Comment by carolinan** [comment]
Moved this to the Gutenberg repo.
