### ISSUE TITLE
 Buttons placed in a block that has the grey palette color as background are sometimes invisible

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#902]
On the default body background:

Buttons placed in a block that has the grey palette color as background are invisible, only the text shows.
**This issue exists with and without  https://github.com/WordPress/twentytwentyone/pull/886.**
On any other light background, the button background turns black and is visible.

default (filled) button on the default background, on hover (yup)
![default](https://user-images.githubusercontent.com/7422055/100602575-57272100-3304-11eb-8829-10ca1f8f2061.png)

With pink (sorry, red) body background, default (filled) button, on hover:
![pink](https://user-images.githubusercontent.com/7422055/100602444-2e9f2700-3304-11eb-88c2-9e729f2e6577.png)

Here, the contrast is too low to be accessible, but low contrast is better than invisible.

Yes, users need to change colors if something is difficult to read: but first, to change it, they need to be able to see it.

In the editor, when adding a button:
![defaultbg-editor](https://user-images.githubusercontent.com/7422055/100602914-cc92f180-3304-11eb-88fa-af3b27839921.png)

With dark mode:
![darkmode](https://user-images.githubusercontent.com/7422055/100605399-28ab4500-3308-11eb-91c8-0a54402d94ac.png)

**This is probably the style we need on top of the grey block background, independent of the body background.**

_Originally posted by @carolinan in https://github.com/WordPress/twentytwentyone/pull/886#issuecomment-735718467_

**Comment by carolinan** [comment]
Is it too confusing for users if the buttons have different colors depending on the parent block background?

**Comment by aristath** [comment]
I think leaving this as-is would be preferable.
If the user wants their button to be a specific color they should select a color. Changing colors based on the parent element's color would be too confusing, and also quite difficult (if not impossible) to implement with the current implementation from the editor without the addition of many more custom scripts and styles in the theme.
If this should be fixed somewhere it should be on the editor side - where we'll need to expose the colors as variables. There are numerous discussions on that topic, and it's not an easy issue to fix.
I'd rather not make assumptions like that in the theme... For now this is something that should be fixed in the content itself (like select colors for the button if it's inside a dark container while using a light theme).

**Comment by carolinan** [comment]
I agree,  I want it to be easy to edit, and I want it to work, but there is no solution.
There should be a contrast warning here like there is for text content.

**Comment by aristath** [comment]
Not that easy to accomplish... 😆 but yeah, I agree with you.
